# Site settings
title: twohlix.com - only unicorns in the future
email: 
description: > # this means to ignore newlines until "baseurl:"
  The personal site of Charles Smith (aka twohlix). Nerd and stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://twohlix.com" # the base hostname & protocol for your site
twitter_username: twohlix
github_username:  twohlix

permalink: "/:year/:month/:title/"

# Build settings
markdown: kramdown
